CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    username        VARCHAR(100) NOT NULL UNIQUE,
    password        VARCHAR(255) NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS training_types (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name   VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS trainees (
    user_id         BIGINT NOT NULL PRIMARY KEY,
    date_of_birth   DATE,
    address         VARCHAR(255),
    CONSTRAINT fk_trainees_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS trainers (
    user_id             BIGINT NOT NULL PRIMARY KEY,
    training_type_id    BIGINT NOT NULL,
    CONSTRAINT fk_trainers_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_trainers_training_type FOREIGN KEY (training_type_id) REFERENCES training_types (id)
);

CREATE TABLE IF NOT EXISTS trainings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id          BIGINT       NOT NULL,
    trainer_id          BIGINT       NOT NULL,
    training_name       VARCHAR(200) NOT NULL,
    training_type_id    BIGINT       NOT NULL,
    training_date       DATE         NOT NULL,
    training_duration   INTEGER      NOT NULL,
    CONSTRAINT fk_trainings_trainee FOREIGN KEY (trainee_id) REFERENCES trainees (user_id),
    CONSTRAINT fk_trainings_trainer FOREIGN KEY (trainer_id) REFERENCES trainers (user_id),
    CONSTRAINT fk_trainings_training_type FOREIGN KEY (training_type_id) REFERENCES training_types (id)
);
